# ============================
# Dockerfile.mlflow — MLflow UI
# ============================
FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY mlruns/ ./mlruns/

EXPOSE 5000

CMD ["mlflow", "ui", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "/mlruns","--allowed-hosts", "*", "--cors-allowed-origins", "*"]

